Update toolboxmatic

diff --git a/toolboxmatic b/toolboxmatic
--- a/toolboxmatic
+++ b/toolboxmatic
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+DEBUG=0
+
 #######################################
 # Display an error message.
 # Arguments:
@@ -8,7 +10,11 @@
 #   0
 #######################################
 err() {
-  echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+  if [[ "$*" != *"DEBUG:"* ]]; then
+    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+  elif [[ "$*" != *"DEBUG:"* && ${DEBUG} == "1" ]]; then
+    echo "[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*" >&2
+  fi
 }
 
 #######################################
@@ -35,19 +41,55 @@ query() {
     export MYSQL_PWD=${DB_PASS}
     q=$*
     cmd="${CLI} -h ${MASTER} -u ${DB_USER} -P ${MA_PORT} -B --skip-column-names -e \"${q}\""
-    err "INFO: Sending query ${cmd}"
+    err "DEBUG: Sending query ${cmd}"
     res=$(eval $cmd)
 }
 
-echo Hi! I am toolboxmatic, your automatic SingleStore Toolbox configurator!
+echo Welcome to toolboxmatic, your automatic SingleStore Toolbox configurator!
 echo =========================================================================
 echo
 
-read -p "Master Aggreator [localhost]: " MASTER
-read -p "Master Aggregator Port [3306]: " MA_PORT
+# A few initial  checks. Is the CLI is installed...
+CLI=`which singlestore`
+
+if [ -z "${CLI}" ]; then
+    CLI=`which memsql`
+elif [ -z "${CLI}" ]; then
+    CLI=`which mysql`
+elif [ -z "${CLI}" ]; then
+    err "ERROR: CLI not found. Please install package singlestore-client. \
+         \For more information visit: https://docs.singlestore.com/db/latest/en/user-and-cluster-administration/cluster-management-with-tools/singlestore-tools-installation/singlestore-client-installation.html"
+    exit 1
+fi
+
+# Let's check if toolbox is installed...
+SDB=`which sdb-toolbox-config`
+
+if [ -z "${SDB}" ]; then
+    err "ERROR: SingleStore Tools are not found. Please install package singlestoredb-toolbox. For more information visit: https://docs.singlestore.com/db/latest/en/user-and-cluster-administration/migrate-from-ops-to-tools/sudo/install-singlestore-tools.html"
+    exit 1
+fi
+
+read -p "Aggregator [localhost]: " MASTER
+read -p "Aggregator Port [3306]: " MA_PORT
 read -p "Username [root]: " DB_USER
-read -p "Password []: " DB_PASS
-read -p "SSH key (enter full path or leave empty for single host deployment) []: " SSH_KEY
+prompt="Password []: "
+while IFS= read -p "${prompt}" -r -s -n 1 char
+do
+    if [[ $char == $'\0' ]]
+    then
+        break
+    fi
+    prompt='*'
+    DB_PASS+="$char"
+done
+echo
+read -p "SSH key []: " SSH_KEY
+
+if [ -z "${SSH_KEY}" ]; then
+    err "ERROR: Sorry. You have more than 1 one host in your cluster but you have not provided a SSH key. Exiting."
+    exit 1
+fi
 
 if [ -z "${MASTER}" ]; then
     MASTER="localhost"
@@ -59,26 +101,6 @@ fi
 
 if [ -z "${DB_USER}" ]; then
     DB_USER="root"
-fi
-
-# Let's check if the CLI is installed...
-CLI=`which singlestore`
-
-if [ -z "${CLI}" ]; then
-    CLI=`which memsql`
-elif [ -z "${CLI}" ]; then
-    CLI=`which mysql`
-elif [ -z "${CLI}" ]; then
-    err "ERROR: CLI not found. Please install package singlestore-client. For more information visit: https://docs.singlestore.com/db/latest/en/user-and-cluster-administration/cluster-management-with-tools/singlestore-tools-installation/singlestore-client-installation.html"
-    exit 1;
-fi
-
-# Let's check if toolbox is installed...
-SDB=`which sdb-toolbox-config`
-
-if [ -z "${SDB}" ]; then
-    err "ERROR: SingleStore Tools are not found. Please install package singlestoredb-toolbox. For more information visit: https://docs.singlestore.com/db/v7.6/en/user-and-cluster-administration/migrate-from-ops-to-tools/sudo/install-singlestore-tools.html"
-    exit 1;
 fi
 
 err "DEBUG: MA   = ${MASTER}"
@@ -111,51 +133,18 @@ if [ ! -z "${TOOLBOX_HOSTS}" ]; then
         case $yn in
             [Yy]* ) reset_toolbox; break;;
             [Nn]* ) exit;;
-            * ) err "ERROR: Please answer yes or no.";;
+            * ) err "INFO: Please answer yes or no.";;
         esac
     done
 fi
 
-isfirst=1
-
 # Let's register all hosts
-for host in $HOSTS
+for host in ${HOSTS}
 do
     err "INFO: Registering host ${host}"
-    if [ ${isfirst} != 1 ]; then
-        if [ -z "${SSH_KEY}" ]; then
-            err "ERROR: Sorry. You have more than 1 one host in your cluster but you have not provided a SSH key. Exiting."
-            exit 1
-        else
-            res=`${SDB} register-host --allow-duplicate-host-fingerprints --host ${host} --identity-file ${SSH_KEY} -y`
-            err "INFO: ${res}"
-        fi
-    else
-	res=`${SDB} register-host --host ${host} --localhost -y`
-        isfirst=0
-    fi
+    res=`${SDB} register-host --allow-duplicate-host-fingerprints --host ${host} --identity-file ${SSH_KEY} -y`
+    err "DEBUG: ${res}"
 done
 
-# Let's add the aggregators
-#singlestore> SELECT HOST,PORT FROM AGGREGATORS;
-#+------------+------+
-#| HOST       | PORT |
-#+------------+------+
-#| 10.0.3.14  | 3306 |
-#| 10.0.3.163 | 3306 |
-#+------------+------+
-err "INFO: Discovering AGGREGATORS..."
-query "SELECT HOST,PORT FROM information_schema.AGGREGATORS"
-err "DEBUG: ${res}"
-
-# And, finally add the leaves
-#singlestore> SELECT HOST,PORT FROM LEAVES;
-#+------------+------+
-#| HOST       | PORT |
-#+------------+------+
-#| 10.0.3.163 | 3307 |
-#| 10.0.3.14  | 3307 |
-#+------------+------+
-err "INFO: Discovering LEAVES..."
-query "SELECT HOST,PORT FROM information_schema.LEAVES"
-err "DEBUG: ${res}"
+res=`sdb-admin list-nodes`
+err "INFO: ${res}"
